---
permalink: storage/task_data_protection_create_a_snapshot_schedule.html 
sidebar: sidebar 
keywords: snapshot schedule, create, volumes, recurring schedule 
summary: Se puede programar la ejecución automática de una copia de Snapshot de un volumen o de varios volúmenes en intervalos concretos. 
---
= Crear una programación de Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se puede programar la ejecución automática de una copia de Snapshot de un volumen o de varios volúmenes en intervalos concretos.

Cuando se configura una programación de Snapshot, se puede elegir entre intervalos de tiempo basados en los días de la semana o los días del mes. Igualmente, se puede crear una programación recurrente y especificar los días, las horas y los minutos antes de que se ejecute la siguiente snapshot.

Si se programa la ejecución de una copia de Snapshot en un período que no sea divisible entre 5 minutos, la copia de Snapshot se ejecutará en el siguiente período que lo sea 5. Por ejemplo, si se programa la ejecución de una copia de Snapshot a las 12:42:00 UTC, se realizará a las 12:45:00 UTC. No se podrá programar la ejecución de una copia de Snapshot en intervalos inferiores a 5 minutos.

.Pasos
. Haga clic en *Protección de datos* > *programas*.
. Haga clic en *Crear programación*.
. En el campo *ID de volumen CSV*, introduzca un ID de volumen único o una lista separada por comas con los ID de volumen que desea incluir en la operación de instantánea.
. Introduzca un nombre de programación nuevo.
. Seleccione un tipo de programación y establezca la programación entre las opciones proporcionadas.
. *Opcional:* Seleccione *Recurring Schedule* para repetir la programación de la instantánea de forma indefinida.
. *Opcional:* Escriba un nombre para la nueva instantánea en el campo *Nuevo nombre de instantánea*.
+
Si se deja el campo vacío, el sistema usará como nombre la hora y la fecha de la creación de la copia de Snapshot.

. *Opcional:* Active la casilla de verificación *incluir instantáneas en replicación cuando se empareja* para asegurarse de que las instantáneas se capturan en la replicación cuando el volumen principal está emparejado.
. Para configurar la retención de la snapshot, seleccione una de las siguientes opciones:
+
** Haga clic en *mantener siempre* para conservar la instantánea en el sistema indefinidamente.
** Haga clic en *establecer período de retención* y utilice los cuadros de número de fecha para elegir un período de tiempo durante el cual el sistema retendrá la instantánea.


. Haga clic en *Crear programación*.

